name: Install

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
        node: [14, 16, 17]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        check-latest: true
    - name: Install
      run: |
        npm install --ignore-scripts
        rm -rf node_modules
        npm install --ignore-scripts
        rm -rf node_modules
        npm install --ignore-scripts
        rm -rf node_modules
        npm install --ignore-scripts
        rm -rf node_modules
        npm install --ignore-scripts
        rm -rf node_modules
