name: puppeteer-llvmbindings

on:
  push:
    paths:
      - '.github/workflows/puppeteer-llvmbindings.yml'
      - 'puppeteer-llvmbindings.js'
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11]
        node: [14, 16, 17]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        check-latest: true
    - name: Install
      run: |
        npm install puppeteer
        node puppeteer-llvmbindings.js
